import type { Metadata } from "next";
import { Pinyon_Script, Cormorant_Garamond } from "next/font/google";
import "./globals.css";

const pinyon = Pinyon_Script({
  subsets: ['latin-ext'],
  weight: '400',
  variable: '--font-pinyon',
})

const cormorant = Cormorant_Garamond({
  subsets: ['latin-ext'],
  variable: '--font-cormorant',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html
  lang="pl"
  className={`${pinyon.variable} ${cormorant.variable}`}
>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
